In [1]:
import numpy as np
matriz_a=np.random.rand(3,3)
matriz_b=np.random.rand(3,3)
soma=matriz_a + matriz_b
print(soma)
produto=np.dot(matriz_a , matriz_b)
print(produto)
transposta_a=np.transpose(matriz_a)
transposta_b=np.transpose(matriz_b)
print(transposta_a)
print(transposta_b)
media_b=np.mean(matriz_b)
desvio_a = np.std(matriz_a)
print(media_b)
print(desvio_a)

[[1.07017102 1.69035149 1.03825037]
 [0.23751687 0.48018305 1.45925591]
 [1.5406931  1.04648734 1.25530491]]
[[1.08310063 1.28954831 1.29942728]
 [0.82993507 0.59098104 0.98848889]
 [0.65389146 1.04611181 0.69960317]]
[[0.6279933  0.07822992 0.73133376]
 [0.74054562 0.11195204 0.55155829]
 [0.84938382 0.96064999 0.29981235]]
[[0.44217772 0.15928695 0.80935934]
 [0.94980587 0.36823101 0.49492905]
 [0.18886654 0.49860592 0.95549256]]
0.5407505511834588
0.3001084412620699
